package com.example.android.colearnassignment

object Constants {
    const val PIC_DATA = "pic_data"
    const val CLIENT_ID = "client_id"
    const val COLLECTION_ID = "2072664"
    const val SEARCH_QUERY = "search_query"
    const val BLACK_AND_WHITE = "black_and_white"
    const val ANY = "any"
    const val PORTRAIT = "portrait"
    const val SQUARE = "square"
    const val LANDSCAPE = "landscape"
    const val LATEST = "latest"
    const val RED = "red"
    const val ORANGE = "orange"
    const val GREEN = "green"
    const val PURPLE = "purple"
    const val YELLOW = "yellow"
    const val BLUE = "blue"
    const val FILTERPARAM = "filterParam"
    const val SEARCHRESULTSFRAGMENT = "SearchResultsFragment"
    const val ADVANCEFILTERFRAGMENT = "AdvanceFilterFragment"
    const val ISFROMFILTERPAGE = "isFromFilterPage"
    const val QUERY = "query"
    const val ORDER_BY = "order_by"
    const val ORIENTATION = "orientation"
    const val COLOR = "color"
    const val RELEVANCE = "relevance"
    const val ANY_COLOR = "any_color"
}